version: "3.10"

services:

  worker:

    build: .

    environment:

      BOT_TOKEN: $BOT_TOKEN

      API_ID: $API_ID

      API_HASH: $API_HASH

      CHANNELS: $CHANNELS

      ADMINS: $ADMINS

      PICS: $PICS

      LOG_CHANNEL: $LOG_CHANNEL

      AUTH_CHANNEL: $AUTH_CHANNEL

      DATABASE_URI: $DATABASE_URI

      DATABASE_NAME: $DATABASE_NAME

      COLLECTION_NAME: $COLLECTION_NAME
      
      INDEX_REQ_CHANNEL: $INDEX_REQ_CHANNEL
      
      P_TTI_SHOW_OFF: $P_TTI_SHOW_OFF
      

      
